package com.jduncan.portfolio.mapper

import com.jduncan.portfolio.dto.CreateProjectRequest
import com.jduncan.portfolio.dto.ProjectResponse
import com.jduncan.portfolio.dto.UpdateProjectRequest
import com.jduncan.portfolio.model.Project
import java.time.LocalDateTime

object ProjectMapper {

  fun Project.toResponse(): ProjectResponse {
    return ProjectResponse(
      id = this.id,
      name = this.name,
      description = this.description,
      image = this.image,
      link = this.link,
      githubLink = this.githubLink,
      technologies = this.technologies,
      role = this.role,
      startDate = this.startDate,
      isPublished = this.isPublished,
      publishedDate = this.publishedDate,
      lastModifiedDate = this.lastModifiedDate
    )
  }

  fun CreateProjectRequest.toEntity(): Project {
    return Project(
      id = 0, // Will be generated by the database
      name = this.name,
      description = this.description,
      image = this.image,
      link = this.link,
      githubLink = this.githubLink,
      technologies = this.technologies,
      role = this.role,
      startDate = this.startDate,
      isPublished = this.isPublished,
      publishedDate = LocalDateTime.now(),
      lastModifiedDate = LocalDateTime.now()
    )
  }

  fun Project.updateFromRequest(request: UpdateProjectRequest): Project {
    return this.copy(
      name = request.name ?: this.name,
      description = request.description ?: this.description,
      image = request.image ?: this.image,
      link = request.link ?: this.link,
      githubLink = request.githubLink ?: this.githubLink,
      technologies = request.technologies ?: this.technologies,
      role = request.role ?: this.role,
      startDate = request.startDate ?: this.startDate,
      isPublished = request.isPublished ?: this.isPublished,
      lastModifiedDate = LocalDateTime.now()
    )
  }

  fun List<Project>.toResponseList(): List<ProjectResponse> {
    return this.map { it.toResponse() }
  }
}
